### ISSUE TITLE
Highlighted words move on the page!

### ISSUE THREAD

**Issue by Grossdm** [benbasson/contexthighlight#2]
On this website: http://www.consumerreports.org/cro/news/2013/10/wireless-charging-pad-reviews/index.htm I selected various words, and every one that I highlighted jumped to the left-most position on every single line in which the word appeared.
Here is a screenshot:

![context highlight example 2015-06-19](https://cloud.githubusercontent.com/assets/836787/8255459/21e223ae-166e-11e5-928b-d3aebe8116e0.jpg)

**Comment by benbasson** [comment]
That's one of the best bugs I've ever seen. I'll look into it.
