### ISSUE TITLE
Does not work with e10s

### ISSUE THREAD

**Issue by bartlibert** [benbasson/contexthighlight#4]
When using this extension in an e10s window, the context menu item to highlight a word is not shown:
![e10s](https://cloud.githubusercontent.com/assets/948770/11418041/801f7ecc-941c-11e5-8240-174fd6a1e372.png)

When I open a non-e10s window, everything works fine:
![normal](https://cloud.githubusercontent.com/assets/948770/11418059/8291f1da-941c-11e5-92fb-3da44a06df2e.png)

This is using Firefox 44.0a2 and version 0.3.6 of the add-on.

**Comment by benbasson** [comment]
Hi, I've just installed 44.0a2 on Windows 7 and I'm not seeing this problem. Could you please let me know what OS version you're on?

The menu item doesn't work, but that's another problem :-)

**Comment by bartlibert** [comment]
I've disabled all my extensions and then enabled them one by one again, and now the menu is indeed present, but it does not do anything still.
